// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using HR.Models.Entity;

namespace HR.Database
{
    public partial class HRSysContext : DbContext
    {
        public HRSysContext()
        {
        }

        public HRSysContext(DbContextOptions<HRSysContext> options)
            : base(options)
        {
        }

        public virtual DbSet<FE_CONSISTENCY_TEST> FE_CONSISTENCY_TEST { get; set; }
        public virtual DbSet<FE_RESUME> FE_RESUME { get; set; }
        public virtual DbSet<FE_RESUME_ATTACHMENT> FE_RESUME_ATTACHMENT { get; set; }
        public virtual DbSet<HR_HUMATTTACH> HR_HUMATTTACH { get; set; }
        public virtual DbSet<HR_HUMIFO_MST> HR_HUMIFO_MST { get; set; }
        public virtual DbSet<HR_HUMSTS_CHGHIS> HR_HUMSTS_CHGHIS { get; set; }
        public virtual DbSet<HR_HUMVAC_RELATE> HR_HUMVAC_RELATE { get; set; }
        public virtual DbSet<HR_INTERVW_HIS> HR_INTERVW_HIS { get; set; }
        public virtual DbSet<HR_JOBTYP> HR_JOBTYP { get; set; }
        public virtual DbSet<HR_JOBTYP_TAG> HR_JOBTYP_TAG { get; set; }
        public virtual DbSet<HR_MESSAGE> HR_MESSAGE { get; set; }
        public virtual DbSet<HR_MESSAGE_TAG> HR_MESSAGE_TAG { get; set; }
        public virtual DbSet<HR_VACANCY_HIS> HR_VACANCY_HIS { get; set; }
        public virtual DbSet<HR_VACMST> HR_VACMST { get; set; }
        public virtual DbSet<HR_VACTYP_RELATE> HR_VACTYP_RELATE { get; set; }
        public virtual DbSet<SY_OPTION> SY_OPTION { get; set; }
        public virtual DbSet<SY_OPTION_TAG> SY_OPTION_TAG { get; set; }
        public virtual DbSet<SY_USER> SY_USER { get; set; }
        public virtual DbSet<VW_HUMIFO_MST> VW_HUMIFO_MST { get; set; }
        public virtual DbSet<VW_HUMVAC_RELATE> VW_HUMVAC_RELATE { get; set; }
        public virtual DbSet<VW_VACHUM_CHGHIS_STAT> VW_VACHUM_CHGHIS_STAT { get; set; }
        public virtual DbSet<VW_VAC_OVERVW> VW_VAC_OVERVW { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("sys");

            modelBuilder.Entity<FE_CONSISTENCY_TEST>(entity =>
            {
                entity.HasKey(e => e.FCT_CST_RSM_ID)
                    .HasName("PK__FE_CONSI__DB19444D32755680");

                entity.HasOne(d => d.FCT_CST_RSM)
                    .WithOne(p => p.FE_CONSISTENCY_TEST)
                    .HasForeignKey<FE_CONSISTENCY_TEST>(d => d.FCT_CST_RSM_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__FE_CONSIS__FCT_C__1AD3FDA4");
            });

            modelBuilder.Entity<FE_RESUME>(entity =>
            {
                entity.HasKey(e => e.FR_RSM_ID)
                    .HasName("PK__FE_RESUM__183856932A1BAB9E");
            });

            modelBuilder.Entity<FE_RESUME_ATTACHMENT>(entity =>
            {
                entity.HasKey(e => new { e.FRA_ACH_RSM_ID, e.FRA_ACH_SEQ })
                    .HasName("PK__FE_RESUM__52FC110147B98A58");

                entity.HasOne(d => d.FRA_ACH_RSM)
                    .WithMany(p => p.FE_RESUME_ATTACHMENT)
                    .HasForeignKey(d => d.FRA_ACH_RSM_ID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__FE_RESUME__FRA_A__19DFD96B");
            });

            modelBuilder.Entity<HR_HUMATTTACH>(entity =>
            {
                entity.HasKey(e => new { e.HAC_ACH_SN, e.HAC_HHI_HUM_SN })
                    .HasName("PK__HR_HUMAT__2861746906E0745B");

                entity.Property(e => e.HAC_ACH_SN).ValueGeneratedOnAdd();

                entity.HasOne(d => d.HAC_HHI_HUM_SNNavigation)
                    .WithMany(p => p.HR_HUMATTTACH)
                    .HasForeignKey(d => d.HAC_HHI_HUM_SN)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__HR_HUMATT__HAC_H__5812160E");
            });

            modelBuilder.Entity<HR_HUMIFO_MST>(entity =>
            {
                entity.HasKey(e => e.HHI_HUM_SN)
                    .HasName("PK__HR_HUMIF__A2E426D01EECD1E5");
            });

            modelBuilder.Entity<HR_HUMSTS_CHGHIS>(entity =>
            {
                entity.HasKey(e => new { e.HSC_CHG_SN, e.HSC_HHI_HUM_SN })
                    .HasName("PK__HR_HUMST__747EAAE939C6334D");

                entity.Property(e => e.HSC_CHG_SN).ValueGeneratedOnAdd();

                entity.HasOne(d => d.HSC_HHI_HUM_SNNavigation)
                    .WithMany(p => p.HR_HUMSTS_CHGHIS)
                    .HasForeignKey(d => d.HSC_HHI_HUM_SN)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__HR_HUMSTS__HSC_H__5629CD9C");
            });

            modelBuilder.Entity<HR_HUMVAC_RELATE>(entity =>
            {
                entity.HasKey(e => new { e.HHV_HHI_HUM_SN, e.HHV_HVM_VAC_SN })
                    .HasName("PK__HR_HUMVA__4FB89D96D56BD15F");

                entity.HasOne(d => d.HHV_HHI_HUM_SNNavigation)
                    .WithMany(p => p.HR_HUMVAC_RELATE)
                    .HasForeignKey(d => d.HHV_HHI_HUM_SN)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__HR_HUMVAC__HHV_H__5535A963");
            });

            modelBuilder.Entity<HR_INTERVW_HIS>(entity =>
            {
                entity.HasKey(e => new { e.HIH_ITV_HIS_SN, e.HIH_HHI_HUM_SN })
                    .HasName("PK__HR_INTER__F83FC2077874933E");

                entity.Property(e => e.HIH_ITV_HIS_SN).ValueGeneratedOnAdd();

                entity.HasOne(d => d.HIH_HHI_HUM_SNNavigation)
                    .WithMany(p => p.HR_INTERVW_HIS)
                    .HasForeignKey(d => d.HIH_HHI_HUM_SN)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__HR_INTERV__HIH_H__571DF1D5");
            });

            modelBuilder.Entity<HR_JOBTYP>(entity =>
            {
                entity.HasKey(e => e.HJT_JOB_SN)
                    .HasName("PK__HR_JOBTY__77E14B1AD89F523D");

                entity.HasOne(d => d.HJT_JOB_TAG_SNNavigation)
                    .WithMany(p => p.HR_JOBTYP)
                    .HasForeignKey(d => d.HJT_JOB_TAG_SN)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__HR_JOBTYP__HJT_J__5441852A");
            });

            modelBuilder.Entity<HR_JOBTYP_TAG>(entity =>
            {
                entity.HasKey(e => e.HJT_TAG_SN)
                    .HasName("PK__HR_JOBTY__1F8C89AB6587272E");
            });

            modelBuilder.Entity<HR_MESSAGE>(entity =>
            {
                entity.HasKey(e => e.HMS_MSG_SN)
                    .HasName("PK__HR_MESSA__6A7A3BECF5E722E2");

                entity.HasOne(d => d.HMS_MSG_MGT_SNNavigation)
                    .WithMany(p => p.HR_MESSAGE)
                    .HasForeignKey(d => d.HMS_MSG_MGT_SN)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__HR_MESSAG__HMS_M__59FA5E80");
            });

            modelBuilder.Entity<HR_MESSAGE_TAG>(entity =>
            {
                entity.HasKey(e => e.HMT_MGT_SN)
                    .HasName("PK__HR_MESSA__10606B10D097E9EA");
            });

            modelBuilder.Entity<HR_VACANCY_HIS>(entity =>
            {
                entity.HasKey(e => new { e.HVH_HIS_SN, e.HVH_HVM_VAC_SN })
                    .HasName("PK__HR_VACAN__3EA763A0324422A9");

                entity.Property(e => e.HVH_HIS_SN).ValueGeneratedOnAdd();

                entity.HasOne(d => d.HVH_HVM_VAC_SNNavigation)
                    .WithMany(p => p.HR_VACANCY_HIS)
                    .HasForeignKey(d => d.HVH_HVM_VAC_SN)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__HR_VACANC__HVH_H__534D60F1");
            });

            modelBuilder.Entity<HR_VACMST>(entity =>
            {
                entity.HasKey(e => e.HVM_VAC_SN)
                    .HasName("PK__HR_VACMS__5949B9A1728B0382");
            });

            modelBuilder.Entity<HR_VACTYP_RELATE>(entity =>
            {
                entity.HasKey(e => new { e.HVT_HVM_VAC_SN, e.HVT_HJT_JOB_SN })
                    .HasName("PK__HR_VACTY__98EE8A2EAFAEA0EB");

                entity.HasOne(d => d.HVT_HVM_VAC_SNNavigation)
                    .WithMany(p => p.HR_VACTYP_RELATE)
                    .HasForeignKey(d => d.HVT_HVM_VAC_SN)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__HR_VACTYP__HVT_H__52593CB8");
            });

            modelBuilder.Entity<SY_OPTION>(entity =>
            {
                entity.HasKey(e => e.SY_OPT_SN)
                    .HasName("PK__SY_OPTIO__FE4A37E4163AE348");

                entity.HasOne(d => d.SY_OPT_SOT_SNNavigation)
                    .WithMany(p => p.SY_OPTION)
                    .HasForeignKey(d => d.SY_OPT_SOT_SN)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__SY_OPTION__SY_OP__59063A47");
            });

            modelBuilder.Entity<SY_OPTION_TAG>(entity =>
            {
                entity.HasKey(e => e.SY_SOT_SN)
                    .HasName("PK__SY_OPTIO__31D697CA89344748");
            });

            modelBuilder.Entity<SY_USER>(entity =>
            {
                entity.HasKey(e => e.SY_USR_ID)
                    .HasName("PK__SY_USER__C186BE075DC41817");
            });

            modelBuilder.Entity<VW_HUMIFO_MST>(entity =>
            {
                entity.ToView("VW_HUMIFO_MST", "dbo");
            });

            modelBuilder.Entity<VW_HUMVAC_RELATE>(entity =>
            {
                entity.ToView("VW_HUMVAC_RELATE", "dbo");
            });

            modelBuilder.Entity<VW_VACHUM_CHGHIS_STAT>(entity =>
            {
                entity.ToView("VW_VACHUM_CHGHIS_STAT", "dbo");
            });

            modelBuilder.Entity<VW_VAC_OVERVW>(entity =>
            {
                entity.ToView("VW_VAC_OVERVW", "dbo");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}