// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("FE_CONSISTENCY_TEST", Schema = "dbo")]
    public partial class FE_CONSISTENCY_TEST
    {
        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string FCT_CST_RSM_ID { get; set; }
        [Required]
        public string FCT_CST_STG_1 { get; set; }
        [Required]
        public string FCT_CST_STG_2 { get; set; }
        [Required]
        public string FCT_CST_STG_3 { get; set; }
        public int FCT_CST_USE_SEC { get; set; }

        [ForeignKey("FCT_CST_RSM_ID")]
        [InverseProperty("FE_CONSISTENCY_TEST")]
        public virtual FE_RESUME FCT_CST_RSM { get; set; }
    }
}