// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("FE_RESUME", Schema = "dbo")]
    public partial class FE_RESUME
    {
        public FE_RESUME()
        {
            FE_RESUME_ATTACHMENT = new HashSet<FE_RESUME_ATTACHMENT>();
        }

        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string FR_RSM_ID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FR_RSM_ADD_DAT { get; set; }
        [Required]
        public byte[] FR_RSM_PHOTO { get; set; }
        [Required]
        public string FR_RSM_BCI { get; set; }
        [Required]
        public string FR_RSM_EXP { get; set; }
        [Required]
        public string FR_RSM_STATUS { get; set; }
        [Required]
        public string FR_RSM_QA { get; set; }
        public bool FR_ISTEMP { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string FR_RSM_PHOTO_TYP { get; set; }

        [InverseProperty("FCT_CST_RSM")]
        public virtual FE_CONSISTENCY_TEST FE_CONSISTENCY_TEST { get; set; }
        [InverseProperty("FRA_ACH_RSM")]
        public virtual ICollection<FE_RESUME_ATTACHMENT> FE_RESUME_ATTACHMENT { get; set; }
    }
}