// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("FE_RESUME_ATTACHMENT", Schema = "dbo")]
    public partial class FE_RESUME_ATTACHMENT
    {
        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string FRA_ACH_RSM_ID { get; set; }
        [Key]
        public int FRA_ACH_SEQ { get; set; }
        [Required]
        public byte[] FRA_ACH_FIL { get; set; }
        [Required]
        [StringLength(150)]
        public string FRA_ACH_NAM { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string FRA_ACH_EXT { get; set; }
        [Required]
        [StringLength(250)]
        public string FRA_ACH_CNT_TYP { get; set; }

        [ForeignKey("FRA_ACH_RSM_ID")]
        [InverseProperty("FE_RESUME_ATTACHMENT")]
        public virtual FE_RESUME FRA_ACH_RSM { get; set; }
    }
}