// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("HR_HUMSTS_CHGHIS", Schema = "dbo")]
    public partial class HR_HUMSTS_CHGHIS
    {
        [Key]
        public int HSC_CHG_SN { get; set; }
        [Key]
        public int HSC_HHI_HUM_SN { get; set; }
        public int HSC_ORI_HHI_STS { get; set; }
        public int HSC_NEW_HHI_STS { get; set; }
        public int HSC_CHG_RSN_SN { get; set; }
        [StringLength(250)]
        public string HSC_CHG_RSN { get; set; }

        [ForeignKey("HSC_HHI_HUM_SN")]
        [InverseProperty("HR_HUMSTS_CHGHIS")]
        public virtual HR_HUMIFO_MST HSC_HHI_HUM_SNNavigation { get; set; }
    }
}