// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("HR_HUMATTTACH", Schema = "dbo")]
    public partial class HR_HUMATTTACH
    {
        [Key]
        public int HAC_ACH_SN { get; set; }
        [Key]
        public int HAC_HHI_HUM_SN { get; set; }
        [Required]
        [StringLength(50)]
        public string HAC_ACH_NAM { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string HAC_ACH_EXT { get; set; }
        [Required]
        [StringLength(250)]
        public string HAC_ACH_CNT_TYP { get; set; }
        [Required]
        public byte[] HAC_ACH_FIL { get; set; }

        [ForeignKey("HAC_HHI_HUM_SN")]
        [InverseProperty("HR_HUMATTTACH")]
        public virtual HR_HUMIFO_MST HAC_HHI_HUM_SNNavigation { get; set; }
    }
}