// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("HR_HUMVAC_RELATE", Schema = "dbo")]
    public partial class HR_HUMVAC_RELATE
    {
        [Key]
        public int HHV_HHI_HUM_SN { get; set; }
        [Key]
        public int HHV_HVM_VAC_SN { get; set; }

        [ForeignKey("HHV_HHI_HUM_SN")]
        [InverseProperty("HR_HUMVAC_RELATE")]
        public virtual HR_HUMIFO_MST HHV_HHI_HUM_SNNavigation { get; set; }
    }
}