// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("HR_HUMIFO_MST", Schema = "dbo")]
    public partial class HR_HUMIFO_MST
    {
        public HR_HUMIFO_MST()
        {
            HR_HUMATTTACH = new HashSet<HR_HUMATTTACH>();
            HR_HUMSTS_CHGHIS = new HashSet<HR_HUMSTS_CHGHIS>();
            HR_HUMVAC_RELATE = new HashSet<HR_HUMVAC_RELATE>();
            HR_INTERVW_HIS = new HashSet<HR_INTERVW_HIS>();
        }

        [Key]
        public int HHI_HUM_SN { get; set; }
        [Required]
        [StringLength(50)]
        public string HHI_HUM_NAM { get; set; }
        public int HHI_HUM_SEX_SN { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string HHI_HUM_TEL { get; set; }
        [StringLength(127)]
        [Unicode(false)]
        public string HHI_HUM_EMAIL { get; set; }
        public int HHI_HUM_SRC_SN { get; set; }
        public int HHI_HUM_STS_SN { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime HHI_HUM_ADD_DAT { get; set; }
        [Required]
        [StringLength(25)]
        [Unicode(false)]
        public string HHI_HUM_ADD_USR { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime HHI_HUM_CHG_DAT { get; set; }
        [Required]
        [StringLength(25)]
        [Unicode(false)]
        public string HHI_HUM_CHG_USR { get; set; }
        public bool HHI_HUM_BLK { get; set; }
        [Required]
        [StringLength(25)]
        [Unicode(false)]
        public string HHI_PPL_USR { get; set; }

        [InverseProperty("HAC_HHI_HUM_SNNavigation")]
        public virtual ICollection<HR_HUMATTTACH> HR_HUMATTTACH { get; set; }
        [InverseProperty("HSC_HHI_HUM_SNNavigation")]
        public virtual ICollection<HR_HUMSTS_CHGHIS> HR_HUMSTS_CHGHIS { get; set; }
        [InverseProperty("HHV_HHI_HUM_SNNavigation")]
        public virtual ICollection<HR_HUMVAC_RELATE> HR_HUMVAC_RELATE { get; set; }
        [InverseProperty("HIH_HHI_HUM_SNNavigation")]
        public virtual ICollection<HR_INTERVW_HIS> HR_INTERVW_HIS { get; set; }
    }
}