// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("HR_JOBTYP", Schema = "dbo")]
    public partial class HR_JOBTYP
    {
        [Key]
        public int HJT_JOB_SN { get; set; }
        public int HJT_JOB_TAG_SN { get; set; }
        [Required]
        [StringLength(150)]
        public string HJT_JOB_NAM { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string HJT_ACT_TYP { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime HJT_JOB_ADD_DAT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime HJT_JOB_UPD_DAT { get; set; }

        [ForeignKey("HJT_JOB_TAG_SN")]
        [InverseProperty("HR_JOBTYP")]
        public virtual HR_JOBTYP_TAG HJT_JOB_TAG_SNNavigation { get; set; }
    }
}