// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("HR_JOBTYP_TAG", Schema = "dbo")]
    public partial class HR_JOBTYP_TAG
    {
        public HR_JOBTYP_TAG()
        {
            HR_JOBTYP = new HashSet<HR_JOBTYP>();
        }

        [Key]
        public int HJT_TAG_SN { get; set; }
        [Required]
        [StringLength(150)]
        public string HJT_TAG_NAM { get; set; }
        [Required]
        [StringLength(1)]
        public string HJT_ACT_TYP { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime HJT_TAG_ADD_DAT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime HJT_TAG_UPD_DAT { get; set; }

        [InverseProperty("HJT_JOB_TAG_SNNavigation")]
        public virtual ICollection<HR_JOBTYP> HR_JOBTYP { get; set; }
    }
}