// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("HR_MESSAGE", Schema = "dbo")]
    public partial class HR_MESSAGE
    {
        [Key]
        public int HMS_MSG_SN { get; set; }
        public int HMS_MSG_MGT_SN { get; set; }
        [Required]
        [StringLength(50)]
        public string HMS_MSG_SUB { get; set; }
        [Required]
        public string HMS_MSG_CONT { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string HMS_MSG_ACT_TYP { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime HMT_MSG_ADD_DAT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime HMT_MSG_UPD_DAT { get; set; }

        [ForeignKey("HMS_MSG_MGT_SN")]
        [InverseProperty("HR_MESSAGE")]
        public virtual HR_MESSAGE_TAG HMS_MSG_MGT_SNNavigation { get; set; }
    }
}