// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("HR_MESSAGE_TAG", Schema = "dbo")]
    public partial class HR_MESSAGE_TAG
    {
        public HR_MESSAGE_TAG()
        {
            HR_MESSAGE = new HashSet<HR_MESSAGE>();
        }

        [Key]
        public int HMT_MGT_SN { get; set; }
        [Required]
        [StringLength(50)]
        public string HMT_MGT_NAM { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string HMT_MGT_ACT_TYP { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime HMT_MGT_ADD_DAT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime HMT_MGT_UPD_DAT { get; set; }
        public int HMT_MGT_SEQ { get; set; }

        [InverseProperty("HMS_MSG_MGT_SNNavigation")]
        public virtual ICollection<HR_MESSAGE> HR_MESSAGE { get; set; }
    }
}