// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("HR_VACTYP_RELATE", Schema = "dbo")]
    public partial class HR_VACTYP_RELATE
    {
        [Key]
        public int HVT_HVM_VAC_SN { get; set; }
        [Key]
        public int HVT_HJT_JOB_SN { get; set; }

        [ForeignKey("HVT_HVM_VAC_SN")]
        [InverseProperty("HR_VACTYP_RELATE")]
        public virtual HR_VACMST HVT_HVM_VAC_SNNavigation { get; set; }
    }
}