// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("SY_OPTION_TAG", Schema = "dbo")]
    public partial class SY_OPTION_TAG
    {
        public SY_OPTION_TAG()
        {
            SY_OPTION = new HashSet<SY_OPTION>();
        }

        [Key]
        public int SY_SOT_SN { get; set; }
        [Required]
        [StringLength(50)]
        public string SY_SOT_NAM { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string SY_SOT_ACT_TYP { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime SY_SOT_ADD_DAT { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime SY_SOT_UPD_DAT { get; set; }

        [InverseProperty("SY_OPT_SOT_SNNavigation")]
        public virtual ICollection<SY_OPTION> SY_OPTION { get; set; }
    }
}