// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Table("SY_USER", Schema = "dbo")]
    public partial class SY_USER
    {
        [Key]
        [StringLength(25)]
        [Unicode(false)]
        public string SY_USR_ID { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string SY_USR_PWD { get; set; }
        [Required]
        [StringLength(127)]
        [Unicode(false)]
        public string SY_USR_EML { get; set; }
        [Required]
        [StringLength(50)]
        public string SY_USR_NAM { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string SY_ACT_TYP { get; set; }
    }
}