// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Keyless]
    public partial class VW_HUMVAC_RELATE
    {
        public int HHV_HHI_HUM_SN { get; set; }
        public int HHV_HVM_VAC_SN { get; set; }
        [Required]
        [StringLength(50)]
        public string HVM_VAC_NAM { get; set; }
    }
}