// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HR.Models.Entity
{
    [Keyless]
    public partial class VW_VACHUM_CHGHIS_STAT
    {
        public int HSC_CHG_SN { get; set; }
        public int HSC_NEW_HHI_STS { get; set; }
        public bool HVM_VAC_STS { get; set; }
    }
}